version: '3.1'

services: 
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - LAMBDA_REMOTE_DOCKER=true
      - EDGE_PORT=4566
      - DEBUG=1
      - SERVICES=s3,cloudformation,sts,dynamodb,iam,sns,sqs,apigateway,cloudwatch,lambda
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - ENDPOINT_URL=http://host.docker.internal:4566
    ports: 
      - '4566-4597:4566-4597'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" 
    command: "aws configure set aws_access_key_id test
      &&  aws configure set aws_secret_access_key test
      && aws configure set region us-east-1"